/**
 * Catalog → Custom Elements compile.
 * Spec: `specs/domain/wc-compile.md`
 */

import type { CatalogEntry, CatalogLayer } from '../storybook/catalog'

export type WcManifestEntry = {
  catalogId: string
  tagName: string
  layer: CatalogLayer
  title: string
}

const CATALOG_ENTRY_RE =
  /\{\s*id: '([^']+)',\s*layer: '([^']+)',\s*title: '([^']+)'/g

export function kebabCatalogId(id: string): string {
  return id
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase()
}

export function catalogIdToTag(id: string): string {
  return `msqdx-${kebabCatalogId(id)}`
}

export function compileWcManifest(catalog: readonly CatalogEntry[]): WcManifestEntry[] {
  return catalog.map((entry) => ({
    catalogId: entry.id,
    tagName: catalogIdToTag(entry.id),
    layer: entry.layer,
    title: entry.title,
  }))
}

export function parseCatalogSource(source: string): Array<{ id: string; layer: string; title: string }> {
  const out: Array<{ id: string; layer: string; title: string }> = []
  CATALOG_ENTRY_RE.lastIndex = 0
  let match: RegExpExecArray | null
  while ((match = CATALOG_ENTRY_RE.exec(source))) {
    out.push({ id: match[1]!, layer: match[2]!, title: match[3]! })
  }
  return out
}

export function renderWcManifestModule(entries: WcManifestEntry[]): string {
  const body = entries
    .map(
      (e) =>
        `  { catalogId: ${JSON.stringify(e.catalogId)}, tagName: ${JSON.stringify(e.tagName)}, layer: ${JSON.stringify(e.layer)}, title: ${JSON.stringify(e.title)} },`,
    )
    .join('\n')
  return `/** Generated by \`pnpm wc:compile\`. Do not edit by hand. */
import type { WcManifestEntry } from '../compile'

export const WC_MANIFEST = [
${body}
] satisfies WcManifestEntry[]
`
}
