import type { Meta, StoryObj } from '@storybook/react-vite'
import { Button } from './Button'

const meta = {
  title: 'Promoted/Button',
  component: Button,
  tags: ['promoted'],
  parameters: {
    // Consumed by the CREATION → Storybook round-trip pinning spec.
    msqdxUiRef: 'fabd43b44a8d4c24adfe14d2a538260a577e788f',
    // CREATION `ds-button` token-bindables emitted as token-path bindings.
    // For the pilot we only need the mappings that our runtime binding bridge can apply.
    tokenBindings: {
      // CREATION default for `variant="primary"` is the primary action fill.
      color: 'color.action.primary',
      radius: 'radius.xl',
    },
  },
} satisfies Meta<typeof Button>

export default meta
type Story = StoryObj<typeof meta>

/** Generated by CREATION library promote (P1). Do not edit human Default stories. */
export const Promoted: Story = {
  args: {
    children: 'Go',
    variant: 'primary',
    size: 'md',
    shape: 'rounded',
  },
}

