import type { Meta, StoryObj } from '@storybook/react-vite'
import { ChatBlockPanel } from './ChatBlockPanel'

const meta = {
  title: 'Promoted/ChatBlockPanel',
  component: ChatBlockPanel,
  tags: ['promoted'],
  parameters: {
  "msqdxUiRef": "92c970ba0688ac9fb39f27b5933b2cceb5066142",
  "tokenBindings": {
    "radius": "radius.control.md"
  }
},
} satisfies Meta<typeof ChatBlockPanel>

export default meta
type Story = StoryObj<typeof meta>

/** Generated by CREATION library promote (P1). Do not edit human Default stories. */
export const Promoted: Story = {
  args: {
  "background": "",
  "radius": ""
},
}
