import type { Meta, StoryObj } from '@storybook/react-vite'
import { Text } from './Text'

const meta = {
  title: 'Promoted/Text',
  component: Text,
  tags: ['promoted'],
  parameters: {
    msqdxUiRef: 'fabd43b44a8d4c24adfe14d2a538260a577e788f',
    tokenBindings: {
      fontFamily: 'typography.heading.h1',
      fontSize: 'typography.heading.h1',
      fontWeight: 'typography.heading.h1',
      lineHeight: 'typography.heading.h1',
      letterSpacing: 'typography.heading.h1',
      color: 'color.neutral.700',
    },
  },
} satisfies Meta<typeof Text>

export default meta
type Story = StoryObj<typeof meta>

/** Generated by CREATION library promote (P1). Do not edit human Default stories. */
export const Promoted: Story = {
  args: {
    children: 'Trust',
    role: 'title',
    slot: 'label',
    textAlign: 'right',
    textDecoration: 'underline',
    width: '400px',
  },
}
