/**
 * Mag PDF tokens — react-pdf StyleSheet for magazine export.
 * Colors: SSOT `../magazine/colors.ts` (twin of HTML Print*).
 *
 * Layout rule: never combine percentage widths with flex `gap` on the same row —
 * yoga adds gap outside the % measure and text spills into the sibling column.
 */

import { StyleSheet } from '@react-pdf/renderer'
import { magazineColors, type MagazineColors } from '../magazine/colors'
import { MAG_FONT_FAMILY, registerMagazinePdfFonts } from './register-mag-fonts'

registerMagazinePdfFonts()

export const magColors = magazineColors

/** DIN A4 in PDF points */
export const MAG_PAGE_WIDTH = 595.28
export const MAG_PAGE_HEIGHT = 841.89

export const MAG_MARGIN_X = 56
export const MAG_MARGIN_TOP = 52
export const MAG_MARGIN_BOTTOM = 60
export const MAG_COLUMN_MAX = 428
export const MAG_FOOTER_H = 28

const BODY_LINE_HEIGHT = 1.32

/** Build Mag StyleSheet from a color palette (theme override hook for apps). */
export function createMagStyles(colors: MagazineColors) {
  return StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: colors.paper,
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 9,
    lineHeight: BODY_LINE_HEIGHT,
    color: colors.ink,
    paddingTop: MAG_MARGIN_TOP,
    paddingBottom: MAG_MARGIN_BOTTOM,
    paddingLeft: MAG_MARGIN_X,
    paddingRight: MAG_MARGIN_X,
  },
  columnShell: {
    width: '100%',
    alignItems: 'center',
  },
  column: {
    width: MAG_COLUMN_MAX,
  },
  footer: {
    position: 'absolute',
    left: MAG_MARGIN_X,
    right: MAG_MARGIN_X,
    bottom: 20,
    flexDirection: 'column',
  },
  footerRule: {
    borderBottomWidth: 0.6,
    borderBottomColor: colors.line,
    marginBottom: 8,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerMeta: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 6.5,
    fontWeight: 400,
    color: colors.muted,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  chapterIndex: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 7,
    fontWeight: 700,
    color: colors.accentInk,
    letterSpacing: 1.4,
    marginBottom: 6,
  },
  eyebrow: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 7,
    fontWeight: 400,
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 1.6,
    marginBottom: 10,
  },
  headline: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 14,
    fontWeight: 700,
    color: colors.ink,
    letterSpacing: -0.28,
    lineHeight: 1.18,
    marginBottom: 12,
    maxWidth: '100%',
  },
  coverHeadline: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 22,
    fontWeight: 700,
    color: colors.ink,
    letterSpacing: -0.45,
    lineHeight: 1.12,
    marginBottom: 16,
    maxWidth: '100%',
  },
  lede: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 10,
    fontWeight: 400,
    color: colors.inkSoft,
    lineHeight: 1.55,
    marginBottom: 22,
    maxWidth: '100%',
  },
  body: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 8.5,
    fontWeight: 400,
    color: colors.inkSoft,
    lineHeight: 1.62,
    marginBottom: 12,
    maxWidth: '100%',
  },
  meta: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 7.5,
    fontWeight: 400,
    color: colors.muted,
    lineHeight: 1.4,
    marginBottom: 4,
    letterSpacing: 0.2,
    maxWidth: '100%',
  },
  chapterGap: {
    marginTop: 2,
    marginBottom: 6,
    width: '100%',
  },
  chapterStacked: {
    marginTop: 28,
    paddingTop: 22,
    borderTopWidth: 0.6,
    borderTopColor: colors.line,
  },
  rule: {
    borderBottomWidth: 0.6,
    borderBottomColor: colors.line,
    marginVertical: 18,
  },
  accentRule: {
    width: 28,
    borderBottomWidth: 2,
    borderBottomColor: colors.accent,
    marginBottom: 20,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
  },
  col: {
    flexDirection: 'column',
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    width: '100%',
  },
  chip: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 6.5,
    fontWeight: 400,
    color: colors.ink,
    borderWidth: 0.6,
    borderColor: colors.line,
    paddingHorizontal: 6,
    paddingVertical: 3,
    marginRight: 5,
    marginBottom: 5,
    maxWidth: '100%',
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
    marginTop: 2,
    width: '100%',
  },
  kpiValue: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 14,
    fontWeight: 700,
    color: colors.ink,
    letterSpacing: -0.3,
  },
  kpiLabel: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 6.5,
    fontWeight: 400,
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 1.1,
    marginTop: 5,
  },
  kpiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginTop: 28,
    paddingTop: 20,
    borderTopWidth: 0.6,
    borderTopColor: colors.line,
    width: '100%',
  },
  kpiCell: {
    width: '25%',
    paddingRight: 10,
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  twoColRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
  },
  twoColCell: {
    width: '50%',
    maxWidth: '50%',
    flexDirection: 'column',
    flexShrink: 1,
    minWidth: 0,
  },
  subEyebrow: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 6,
    fontWeight: 400,
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 1.3,
    marginBottom: 10,
  },
  personaRow: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'flex-start',
  },
  personaCell: {
    width: '50%',
    maxWidth: '50%',
    paddingTop: 14,
    paddingBottom: 4,
    paddingRight: 12,
    borderTopWidth: 1.25,
    borderTopColor: colors.ink,
    flexShrink: 1,
    minWidth: 0,
  },
  personaCellLast: {
    width: '50%',
    maxWidth: '50%',
    paddingTop: 14,
    paddingBottom: 4,
    paddingLeft: 12,
    borderTopWidth: 1.25,
    borderTopColor: colors.ink,
    flexShrink: 1,
    minWidth: 0,
  },
  personaSpread: {
    width: '100%',
    paddingTop: 8,
    borderTopWidth: 1.25,
    borderTopColor: colors.ink,
  },
  personaName: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 11,
    fontWeight: 700,
    color: colors.ink,
    letterSpacing: -0.2,
    marginBottom: 8,
    maxWidth: '100%',
  },
  personaBio: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 8,
    fontWeight: 400,
    color: colors.inkSoft,
    lineHeight: 1.5,
    marginTop: 10,
    marginBottom: 6,
    maxWidth: '100%',
  },
  rankedIndex: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 8,
    fontWeight: 700,
    color: colors.accentInk,
    width: 18,
    marginRight: 6,
  },
  rankedIndexCompact: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 7.5,
    fontWeight: 700,
    color: colors.accentInk,
    width: 14,
    marginRight: 5,
  },
  rankedTextCol: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  rankedLabel: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 8.5,
    fontWeight: 400,
    color: colors.ink,
    lineHeight: 1.5,
    maxWidth: '100%',
  },
  rankedLabelCompact: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 7.5,
    fontWeight: 400,
    color: colors.ink,
    lineHeight: 1.42,
    maxWidth: '100%',
  },
  rankedMetaCompact: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 6.5,
    fontWeight: 400,
    color: colors.muted,
    lineHeight: 1.4,
    maxWidth: '100%',
  },
  rankedMeta: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 7.5,
    fontWeight: 400,
    color: colors.muted,
    lineHeight: 1.4,
    maxWidth: '100%',
  },
  rankedRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.line,
  },
  rankedRowCompact: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
    marginBottom: 7,
    paddingBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.line,
  },
  tableHeader: {
    flexDirection: 'row',
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: colors.ink,
    paddingBottom: 7,
    marginBottom: 2,
    marginTop: 4,
  },
  tableRow: {
    flexDirection: 'row',
    width: '100%',
    borderBottomWidth: 0.5,
    borderBottomColor: colors.line,
    paddingVertical: 7,
  },
  tableCell: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 8,
    fontWeight: 400,
    color: colors.inkSoft,
    paddingRight: 6,
    width: '100%',
    maxWidth: '100%',
  },
  tableHeadCell: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 6.5,
    fontWeight: 400,
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    paddingRight: 6,
    width: '100%',
    maxWidth: '100%',
  },
  traitTrack: {
    height: 2,
    width: '100%',
    backgroundColor: colors.track,
    marginTop: 3,
    marginBottom: 10,
  },
  traitTrackCompact: {
    height: 1.5,
    width: '100%',
    backgroundColor: colors.track,
    marginTop: 2,
    marginBottom: 3,
  },
  traitFill: {
    height: 2,
    backgroundColor: colors.accent,
  },
  traitName: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 7.5,
    fontWeight: 400,
    color: colors.muted,
    flexGrow: 1,
    flexShrink: 1,
    maxWidth: '82%',
    paddingRight: 6,
  },
  traitPct: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 7.5,
    fontWeight: 400,
    color: colors.muted,
    width: 28,
    textAlign: 'right',
  },
  ledgerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    width: '100%',
    borderBottomWidth: 0.5,
    borderBottomColor: colors.line,
    paddingVertical: 12,
  },
  ledgerScore: {
    fontFamily: MAG_FONT_FAMILY,
    fontSize: 13,
    fontWeight: 700,
    width: 28,
    marginRight: 10,
  },
  pullQuote: {
    flexDirection: 'row',
    width: '100%',
    marginTop: 8,
    marginBottom: 18,
  },
  pullQuoteBar: {
    width: 2.5,
    marginRight: 12,
    backgroundColor: colors.accent,
    alignSelf: 'stretch',
  },
  pullQuoteBody: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    flexDirection: 'column',
    paddingVertical: 2,
  },
  washBox: {
    backgroundColor: colors.wash,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginTop: 18,
    marginBottom: 8,
    width: '100%',
  },
  distGrid: {
    flexDirection: 'row',
    width: '100%',
    marginTop: 10,
    paddingTop: 16,
    borderTopWidth: 0.6,
    borderTopColor: colors.line,
  },
  distCol: {
    width: '33.333%',
    maxWidth: '33.333%',
    paddingRight: 10,
    flexShrink: 1,
    minWidth: 0,
  },
  sectionBlock: {
    marginTop: 24,
    width: '100%',
  },
  coverMetaBlock: {
    marginBottom: 22,
    width: '100%',
  },
})
}

export const magStyles = createMagStyles(magColors)
