#!/usr/bin/env node
/**
 * Compile CATALOG → packages/ui/src/wc/generated/manifest.ts
 * Spec: specs/domain/wc-compile.md
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const catalogPath = join(root, 'packages/ui/src/storybook/catalog.ts')
const outDir = join(root, 'packages/ui/src/wc/generated')
const outPath = join(outDir, 'manifest.ts')

function kebabCatalogId(id) {
  return id
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase()
}

function catalogIdToTag(id) {
  return `msqdx-${kebabCatalogId(id)}`
}

const CATALOG_ENTRY_RE =
  /\{\s*id: '([^']+)',\s*layer: '([^']+)',\s*title: '([^']+)'/g

const source = readFileSync(catalogPath, 'utf8')
const entries = []
let match
CATALOG_ENTRY_RE.lastIndex = 0
while ((match = CATALOG_ENTRY_RE.exec(source))) {
  entries.push({
    catalogId: match[1],
    tagName: catalogIdToTag(match[1]),
    layer: match[2],
    title: match[3],
  })
}

if (!entries.length) {
  throw new Error('wc:compile found no catalog entries')
}

const tags = new Set(entries.map((e) => e.tagName))
if (tags.size !== entries.length) {
  throw new Error('wc:compile produced duplicate tags')
}

const body = entries
  .map(
    (e) =>
      `  { catalogId: ${JSON.stringify(e.catalogId)}, tagName: ${JSON.stringify(e.tagName)}, layer: ${JSON.stringify(e.layer)}, title: ${JSON.stringify(e.title)} },`,
  )
  .join('\n')

const moduleSource = `/** Generated by \`pnpm wc:compile\`. Do not edit by hand. */
import type { WcManifestEntry } from '../compile'

export const WC_MANIFEST = [
${body}
] satisfies WcManifestEntry[]
`

mkdirSync(outDir, { recursive: true })
writeFileSync(outPath, moduleSource)
console.log(`wc:compile wrote ${entries.length} tags → ${outPath}`)
